services:
  - type: web
    name: hgu-lifeshot-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: CORS_ORIGINS
        value: "*"
